### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by laminko** [laminko/wBlog#1]
- [x] add user review page and make available for root and admin.
- [x] update the code for Total comments.
- [x] make demo site and add demo link.
- [x] add `search` feature.
- [ ] to support `search` using Myanmar (Burmese).
- [ ] add markdown editor that supports common-mark.

**Comment by laminko** [comment]
just updated labels.
